"{\
	'general':\
	{\
		'name':'Test',\
		'instance':8,\
		'interval':1000,\
		'print_verbosity':2\
	},\
	'components':[\
    {\
      'name':'Analog',\
      'params':[\
        4,\
        8,\
        false,\
        false,\
        false,\
        false,\
        false,\
        false,\
        0,\
        0,\
        0,\
        0,\
        0,\
        0,\
        25.0\
      ]\
    },\
		{\
			'name':'Multiplexer',\
			'params':[113,8,true, 5000]\
		},\
		{\
			'name':'DS3231',\
			'params':[12, false, true]\
		},\
    {\
      'name':'Interrupt_Manager',\
      'params':[0]\
    },\
    {\
      'name':'Sleep_Manager',\
      'params':[true,false,1]\
    },\
    {\
      'name':'SD',\
      'params': 'default'\
    },\
    {\
      'name':'LoRa',\
      'params':[\
        255,\
        8,\
        20,\
        3,\
        200\
      ]\
    }\
	]\
}"
